spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

kamis:
  api:
    key: ${KAMIS_API_KEY}
    cert-id: ${KAMIS_ID}

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0
  send-default-pii: true
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  server:
    port: 9000
  metrics:
    tags:
      application: ${spring.application.name}
